# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_bookM_import.ui'
#
# Created: Sat Jun 18 00:06:56 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_import(object):
    def setupUi(self, Dialog_import):
        Dialog_import.setObjectName("Dialog_import")
        Dialog_import.resize(855, 435)
        self.groupBox = QtWidgets.QGroupBox(Dialog_import)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 861, 81))
        self.groupBox.setStyleSheet("background-image: url(:/new/prefix1/resources/background4.jpg);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 841, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bookM_path_label = QtWidgets.QLabel(self.layoutWidget)
        self.bookM_path_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.bookM_path_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bookM_path_label.setObjectName("bookM_path_label")
        self.horizontalLayout.addWidget(self.bookM_path_label)
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(11, 40, 841, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.textview_bookM_file = QtWidgets.QTextBrowser(self.splitter)
        self.textview_bookM_file.setObjectName("textview_bookM_file")
        self.pushButton_bookM_select = QtWidgets.QPushButton(self.splitter)
        self.pushButton_bookM_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bookM_select.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_bookM_select.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_bookM_select.setIcon(icon)
        self.pushButton_bookM_select.setFlat(True)
        self.pushButton_bookM_select.setObjectName("pushButton_bookM_select")
        self.pushButton_bookM_delSubmit = QtWidgets.QPushButton(self.splitter)
        self.pushButton_bookM_delSubmit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bookM_delSubmit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_bookM_delSubmit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_bookM_delSubmit.setIcon(icon1)
        self.pushButton_bookM_delSubmit.setFlat(True)
        self.pushButton_bookM_delSubmit.setObjectName("pushButton_bookM_delSubmit")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_import)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 80, 861, 421))
        self.groupBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBox_2.setStyleSheet("background-image: url(:/new/prefix1/resources/background4.jpg);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 64, 491, 261))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textView_bookM_detail = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textView_bookM_detail.setGeometry(QtCore.QRect(0, 0, 491, 261))
        self.textView_bookM_detail.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        self.textView_bookM_detail.setObjectName("textView_bookM_detail")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.bookM_detail_label = QtWidgets.QLabel(self.groupBox_2)
        self.bookM_detail_label.setGeometry(QtCore.QRect(220, 20, 48, 20))
        self.bookM_detail_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.bookM_detail_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bookM_detail_label.setObjectName("bookM_detail_label")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox_2)
        self.buttonBox.setGeometry(QtCore.QRect(510, 320, 341, 32))
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.splitter_5 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_5.setGeometry(QtCore.QRect(550, 40, 291, 31))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.bookM_col_label = QtWidgets.QLabel(self.splitter_2)
        self.bookM_col_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.bookM_col_label.setObjectName("bookM_col_label")
        self.comboBox_bookM_column = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_bookM_column.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        self.comboBox_bookM_column.setObjectName("comboBox_bookM_column")
        self.bookM_type_label = QtWidgets.QLabel(self.splitter_2)
        self.bookM_type_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.bookM_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bookM_type_label.setObjectName("bookM_type_label")
        self.comboBox_bookM_type = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_bookM_type.setObjectName("comboBox_bookM_type")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_9 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_9.setGeometry(QtCore.QRect(550, 160, 301, 111))
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.bookM_column2_label = QtWidgets.QLabel(self.splitter_6)
        self.bookM_column2_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.bookM_column2_label.setObjectName("bookM_column2_label")
        self.comboBox_repSelect = QtWidgets.QComboBox(self.splitter_6)
        self.comboBox_repSelect.setObjectName("comboBox_repSelect")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.bookM_noise_label = QtWidgets.QLabel(self.splitter_7)
        self.bookM_noise_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.bookM_noise_label.setObjectName("bookM_noise_label")
        self.lineEdit_bookM_noise = QtWidgets.QLineEdit(self.splitter_7)
        self.lineEdit_bookM_noise.setObjectName("lineEdit_bookM_noise")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.bookM_replace_label = QtWidgets.QLabel(self.splitter_8)
        self.bookM_replace_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.bookM_replace_label.setObjectName("bookM_replace_label")
        self.lineEdit_bookM_replace = QtWidgets.QLineEdit(self.splitter_8)
        self.lineEdit_bookM_replace.setObjectName("lineEdit_bookM_replace")
        self.splitter_4 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_4.setGeometry(QtCore.QRect(770, 280, 76, 34))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.pushButton_repEnter = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_repEnter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_repEnter.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/enter-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_repEnter.setIcon(icon2)
        self.pushButton_repEnter.setFlat(True)
        self.pushButton_repEnter.setObjectName("pushButton_repEnter")
        self.pushButton_write = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_write.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_write.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/upload-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_write.setIcon(icon3)
        self.pushButton_write.setFlat(True)
        self.pushButton_write.setObjectName("pushButton_write")
        self.splitter_10 = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter_10.setGeometry(QtCore.QRect(730, 80, 111, 34))
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.pushButton_selectSym = QtWidgets.QPushButton(self.splitter_10)
        self.pushButton_selectSym.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_selectSym.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/select-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_selectSym.setIcon(icon4)
        self.pushButton_selectSym.setFlat(True)
        self.pushButton_selectSym.setObjectName("pushButton_selectSym")
        self.pushButton_check = QtWidgets.QPushButton(self.splitter_10)
        self.pushButton_check.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_check.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        self.pushButton_check.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/tag-search-filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_check.setIcon(icon5)
        self.pushButton_check.setFlat(True)
        self.pushButton_check.setObjectName("pushButton_check")
        self.pushButton_view = QtWidgets.QPushButton(self.splitter_10)
        self.pushButton_view.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_view.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view.setIcon(icon6)
        self.pushButton_view.setFlat(True)
        self.pushButton_view.setObjectName("pushButton_view")

        self.retranslateUi(Dialog_import)
        self.buttonBox.accepted.connect(Dialog_import.accept)
        self.buttonBox.rejected.connect(Dialog_import.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_import)

    def retranslateUi(self, Dialog_import):
        _translate = QtCore.QCoreApplication.translate
        Dialog_import.setWindowTitle(_translate("Dialog_import", "Dialog"))
        self.bookM_path_label.setText(_translate("Dialog_import", "Further Filtering"))
        self.bookM_detail_label.setText(_translate("Dialog_import", "Details"))
        self.bookM_col_label.setText(_translate("Dialog_import", "Column"))
        self.bookM_type_label.setText(_translate("Dialog_import", "Type"))
        self.bookM_column2_label.setText(_translate("Dialog_import", "Column"))
        self.bookM_noise_label.setText(_translate("Dialog_import", "Noise Char"))
        self.bookM_replace_label.setText(_translate("Dialog_import", "Replace With"))

import GUI.rs_rc
