# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jul  4 23:11:55 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1229, 565)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.left_group = QtWidgets.QGroupBox(self.centralWidget)
        self.left_group.setGeometry(QtCore.QRect(0, 0, 171, 551))
        self.left_group.setStyleSheet("background-image: url(:/new/prefix1/resources/background5.jpg);")
        self.left_group.setTitle("")
        self.left_group.setObjectName("left_group")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.left_group)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Dashboard = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Dashboard.setStyleSheet("color: rgb(230, 230, 230);\n"
"font: 75 18pt \"Bitstream Charter\";")
        self.Dashboard.setAlignment(QtCore.Qt.AlignCenter)
        self.Dashboard.setObjectName("Dashboard")
        self.verticalLayout.addWidget(self.Dashboard)
        self.Dashboard_group_flter = QtWidgets.QGroupBox(self.centralWidget)
        self.Dashboard_group_flter.setGeometry(QtCore.QRect(170, 0, 1061, 151))
        self.Dashboard_group_flter.setStyleSheet("background-image: url(:/new/prefix1/resources/background4.jpg);")
        self.Dashboard_group_flter.setTitle("")
        self.Dashboard_group_flter.setObjectName("Dashboard_group_flter")
        self.MyLib_filter_label = QtWidgets.QLabel(self.Dashboard_group_flter)
        self.MyLib_filter_label.setGeometry(QtCore.QRect(0, 40, 91, 31))
        self.MyLib_filter_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.MyLib_filter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MyLib_filter_label.setObjectName("MyLib_filter_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Dashboard_group_flter)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 9, 961, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.MyLib_filter_fileSelector = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.MyLib_filter_fileSelector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MyLib_filter_fileSelector.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MyLib_filter_fileSelector.setIcon(icon)
        self.MyLib_filter_fileSelector.setFlat(True)
        self.MyLib_filter_fileSelector.setObjectName("MyLib_filter_fileSelector")
        self.gridLayout.addWidget(self.MyLib_filter_fileSelector, 0, 1, 1, 1)
        self.MyLib_filter_start = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.MyLib_filter_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MyLib_filter_start.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MyLib_filter_start.setIcon(icon1)
        self.MyLib_filter_start.setDefault(False)
        self.MyLib_filter_start.setFlat(True)
        self.MyLib_filter_start.setObjectName("MyLib_filter_start")
        self.gridLayout.addWidget(self.MyLib_filter_start, 0, 2, 1, 1)
        self.MyLib_filter_textview = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.MyLib_filter_textview.setStyleSheet("")
        self.MyLib_filter_textview.setObjectName("MyLib_filter_textview")
        self.gridLayout.addWidget(self.MyLib_filter_textview, 0, 0, 1, 1)
        self.MyLib_filter_progressbar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.MyLib_filter_progressbar.setProperty("value", 0)
        self.MyLib_filter_progressbar.setObjectName("MyLib_filter_progressbar")
        self.gridLayout.addWidget(self.MyLib_filter_progressbar, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/funnel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(170, 150, 1061, 161))
        self.groupBox.setStyleSheet("background-image: url(:/new/prefix1/resources/background4.jpg);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.MyLib_BookM_label = QtWidgets.QLabel(self.groupBox)
        self.MyLib_BookM_label.setGeometry(QtCore.QRect(10, 30, 131, 71))
        self.MyLib_BookM_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.MyLib_BookM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MyLib_BookM_label.setObjectName("MyLib_BookM_label")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(270, 10, 561, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_importDB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_importDB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_importDB.setMouseTracking(False)
        self.pushButton_importDB.setAutoFillBackground(False)
        self.pushButton_importDB.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_importDB.setIcon(icon4)
        self.pushButton_importDB.setFlat(True)
        self.pushButton_importDB.setObjectName("pushButton_importDB")
        self.gridLayout_2.addWidget(self.pushButton_importDB, 0, 0, 1, 1)
        self.pushButton_checkOut = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_checkOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_checkOut.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/Check_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_checkOut.setIcon(icon5)
        self.pushButton_checkOut.setFlat(True)
        self.pushButton_checkOut.setObjectName("pushButton_checkOut")
        self.gridLayout_2.addWidget(self.pushButton_checkOut, 1, 1, 1, 1)
        self.pushButton_checkIn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_checkIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_checkIn.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/Check_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_checkIn.setIcon(icon6)
        self.pushButton_checkIn.setFlat(True)
        self.pushButton_checkIn.setObjectName("pushButton_checkIn")
        self.gridLayout_2.addWidget(self.pushButton_checkIn, 0, 1, 1, 1)
        self.pushButton_search = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_search.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search.setIcon(icon7)
        self.pushButton_search.setFlat(True)
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout_2.addWidget(self.pushButton_search, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 310, 1061, 111))
        self.groupBox_2.setStyleSheet("background-image: url(:/new/prefix1/resources/background4.jpg);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.MyLib_BorrM_label = QtWidgets.QLabel(self.groupBox_2)
        self.MyLib_BorrM_label.setGeometry(QtCore.QRect(10, 30, 161, 41))
        self.MyLib_BorrM_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.MyLib_BorrM_label.setObjectName("MyLib_BorrM_label")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(270, 10, 561, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_createBorr = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_createBorr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_createBorr.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/create_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_createBorr.setIcon(icon8)
        self.pushButton_createBorr.setFlat(True)
        self.pushButton_createBorr.setObjectName("pushButton_createBorr")
        self.gridLayout_3.addWidget(self.pushButton_createBorr, 0, 0, 1, 1)
        self.pushButton_modifyBorr = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_modifyBorr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_modifyBorr.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_modifyBorr.setIcon(icon9)
        self.pushButton_modifyBorr.setFlat(True)
        self.pushButton_modifyBorr.setObjectName("pushButton_modifyBorr")
        self.gridLayout_3.addWidget(self.pushButton_modifyBorr, 0, 1, 1, 1)
        self.pushButton_viewBorr = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_viewBorr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_viewBorr.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_viewBorr.setIcon(icon10)
        self.pushButton_viewBorr.setFlat(True)
        self.pushButton_viewBorr.setObjectName("pushButton_viewBorr")
        self.gridLayout_3.addWidget(self.pushButton_viewBorr, 1, 0, 1, 1)
        self.pushButton_deleteBorr = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_deleteBorr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_deleteBorr.setStyleSheet("font: 75 10pt \"Bitstream Charter\";")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleteBorr.setIcon(icon11)
        self.pushButton_deleteBorr.setFlat(True)
        self.pushButton_deleteBorr.setObjectName("pushButton_deleteBorr")
        self.gridLayout_3.addWidget(self.pushButton_deleteBorr, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 420, 1061, 131))
        self.groupBox_3.setStyleSheet("background-image: url(:/new/prefix1/resources/background4.jpg);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.MyLib_fineM_label = QtWidgets.QLabel(self.groupBox_3)
        self.MyLib_fineM_label.setGeometry(QtCore.QRect(10, 40, 161, 41))
        self.MyLib_fineM_label.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.MyLib_fineM_label.setObjectName("MyLib_fineM_label")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(270, 10, 561, 111))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_checkFIne = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_checkFIne.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_checkFIne.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/check_fine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_checkFIne.setIcon(icon12)
        self.pushButton_checkFIne.setFlat(True)
        self.pushButton_checkFIne.setObjectName("pushButton_checkFIne")
        self.gridLayout_4.addWidget(self.pushButton_checkFIne, 0, 0, 1, 1)
        self.pushButton_setting = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        self.pushButton_setting.setIcon(icon2)
        self.pushButton_setting.setFlat(True)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.gridLayout_4.addWidget(self.pushButton_setting, 0, 1, 1, 1)
        self.pushButton_checkOverdue = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_checkOverdue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_checkOverdue.setStyleSheet("font: 75 12pt \"Bitstream Charter\";")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/new/prefix1/resources/deadline-head-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_checkOverdue.setIcon(icon13)
        self.pushButton_checkOverdue.setFlat(True)
        self.pushButton_checkOverdue.setObjectName("pushButton_checkOverdue")
        self.gridLayout_4.addWidget(self.pushButton_checkOverdue, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Dashboard.setText(_translate("MainWindow", "MyLib"))
        self.MyLib_filter_label.setText(_translate("MainWindow", "Data Filter"))
        self.MyLib_filter_textview.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.MyLib_BookM_label.setText(_translate("MainWindow", "Book Management"))
        self.pushButton_importDB.setText(_translate("MainWindow", "Import database"))
        self.pushButton_checkOut.setText(_translate("MainWindow", "Check out"))
        self.pushButton_checkIn.setText(_translate("MainWindow", "Check In"))
        self.pushButton_search.setText(_translate("MainWindow", "Book Search and Availability"))
        self.MyLib_BorrM_label.setText(_translate("MainWindow", "Borrower Management"))
        self.pushButton_createBorr.setText(_translate("MainWindow", "Create Borrower"))
        self.pushButton_modifyBorr.setText(_translate("MainWindow", "Modify Borrower"))
        self.pushButton_viewBorr.setText(_translate("MainWindow", "View Borrower"))
        self.pushButton_deleteBorr.setText(_translate("MainWindow", "Delete Borrower"))
        self.MyLib_fineM_label.setText(_translate("MainWindow", "Fine Management"))
        self.pushButton_checkFIne.setText(_translate("MainWindow", "Check Fine"))
        self.pushButton_setting.setText(_translate("MainWindow", "Setting"))
        self.pushButton_checkOverdue.setText(_translate("MainWindow", "Check Overdue"))

import GUI.rs_rc
